### NUMPY

In [4]:
import numpy as np

###### 1) 배열(ndarray) 다루기

In [5]:
a = np.array([1, 2, 3, 4, 5, 6], dtype='i')
a

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [6]:
a.ndim

1

In [7]:
a.shape

(6,)

In [8]:
a.dtype

dtype('int32')

In [9]:
a.astype('f')

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [10]:
a.astype('O')

array([1, 2, 3, 4, 5, 6], dtype=object)

기호 | <center>b</center> | **i** | i8 | u | f | O  
- | - | - | - | - | - | -
 타입 | **boolean** | int32 | int64 | uint32 | float32 | object

###### 2) 배열 생성

- zeros, ones('scalar/tuple/list', dtype=)
- zeros_like(다른 배열), ones_like
- empty
- arange(시작, 끝(포함x), 단계)
- linespace(시작, 끝(포함o), 단계)
- logspace(시작, 끝(포함o), 단계)
- rand
- randn

In [23]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [21]:
zeros = np.zeros((4, 5), dtype='O')
zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=object)

In [26]:
zeros_2 = np.zeros_like(ones)
zeros_2

array([0., 0., 0., 0., 0.])

In [17]:
empty = np.empty((4, 5))
empty

array([[0.00000000e+000, 3.10503638e+231, 5.43472210e-323,
        0.00000000e+000, 3.64661140e-306],
       [5.30276956e+180, 3.31033942e-033, 4.57222660e-071,
        4.26048622e-086, 3.35810380e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 1.57351589e+161],
       [1.17449169e+165, 5.87699004e-062, 4.75959157e-038,
        7.10889652e-144, 1.50008929e+248]])

In [18]:
linspace = np.linspace(0, 100, 5)
linspace

array([  0.,  25.,  50.,  75., 100.])

In [31]:
logspace = np.logspace(0, 1, 5)
logspace

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [15]:
np.inf

inf

In [17]:
np.nan #not a number

nan

* Numpy의 강점 1. 벡터화 연산

In [183]:
2 * a

array([ 2,  4,  6,  8, 10, 12])

- Numpy의 강점 2. 변환

In [186]:
a = a.reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

- Numpy의 강점 3. 배열 인덱싱 ( = query 기능 )

In [206]:
a[[1, 0], :]

array([[4, 5, 6],
       [1, 2, 3]])

In [207]:
a[:, [2, 0, 1]]

array([[3, 1, 2],
       [6, 4, 5]])

In [196]:
a%2 == 0

array([[False,  True, False],
       [ True, False,  True]])

In [189]:
a[a%2 == 0]

array([2, 4, 6])

In [197]:
a[0, :] # slicing

array([1, 2, 3])

In [202]:
idx = np.array([0, 2])

In [203]:
a[0, idx]

array([1, 3])

In [204]:
idx2 = np.array([0, 0, 1, 1, 1, 2])

In [205]:
a[1, idx2]

array([4, 4, 5, 5, 5, 6])

###### 2) 난수 발생

- randint(시작, 끝, size='scalar' or 'tuple/list')  
- 

In [153]:
age = np.random.randint(1, 100, size=(3, 5))
age[:10]

array([[25, 99, 65, 41, 93],
       [27, 78, 31, 70, 99],
       [43, 35, 80, 86, 67]])